name: Cache Trophy SVG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"   # har dushanba

jobs:
  cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download trophy SVG
        run: |
          mkdir -p assets
          curl -L "https://github-profile-trophy.vercel.app/?username=Adamd3vs&theme=tokyonight&no-frame=true&row=1&margin-w=15" \
            -o assets/trophy.svg

      - name: Commit cached trophy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/trophy.svg
            git commit -m "chore: update cached trophy"
            git push
          fi
